---
title: "1 Install R/R Studio"
---

::: callout-note
## 🎯 Learning goals

After working through Tutorial 2, you'll be able to...

- **explain and use** the pipe (`|>`) to connect steps in a workflow
:::

## Base-R vs. tidyverse & coding style

There are two "ways" of using R: via Base-R or via the [tidyverse](https://www.tidyverse.org/), [see this overview for a comparison](https://towardsdatascience.com/tidyverse-vs-base-r-how-to-choose-the-best-framework-for-you-29b702bdb384).

Base-R includes all functions that come with initially installing R. A more recent development is the tidyverse, a collection of additional packages (and coding conventions) that is especially suited for beginners. Tidyverse was developed by Hadley Wickham and his team at RStudio (the interface we use for programming with R).

Best practice when coding with R is to either stick to Base-R or the tidyverse, as this makes your code more streamlined and readabile. In this class, we will rely on the tidyverse. You will learn a little bit of Base-R in tutorials 2-3 to know how to read this code (e.g., when stumbling across online forums when looking for R-related code solutions). However, we will then rely on tidyverse in subsequent tutorials.

This also means that I will use the [tidyverse coding style](https://style.tidyverse.org/). With this coding style, we make sure to consistently name things (e.g., with lower letters), use blank spaces, where needed. In short, it makes our code more readable.

If your're interested in this, see a nice summary by IfKW scholar Lara Kobilke [here](https://lkobilke.github.io/introduction_to_R/tutorial-good-coding-style-project-management.html).

## 
